### ISSUE TITLE
Coach Delete Issue

### ISSUE THREAD

**Issue by kazimfriendly** [halfbug/cocpanel#27]
If we delete the coach, in one scenario, it through this error.

![image](https://cloud.githubusercontent.com/assets/6890846/26024521/1d41446e-37ec-11e7-93ec-840a013351d5.png)

**Comment by halfbug** [comment]
unable to reproduce it please guide

**Comment by kazimfriendly** [comment]
Very easy to reproduce, just add one new coach and then try to delete it witthout adding any package to it.
